spring:
  application:
    name: dubbo-provider

dubbo:
  scan:
    base-packages: org.example.service.impl

  registry:
    timeout: 5000
    address: zookeeper://127.0.0.1:12181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

  protocol:
    name: dubbo
    port: -1
  config-center:
    timeout: 5000
  metadata-report:
    timeout: 5000

  consumer:
    version: 1.0.0
